name: AWS Lambda Deploy
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # ソースコードのチェックアウト
      - name: Checkout source
        uses: actions/checkout@v3

      # AWSの認証情報を設定
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions

      # AWS認証が成功しているか確認
      - name: Verify AWS Role Access
        run: aws sts get-caller-identity

      # Node.js環境のセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # パッケージのインストール
      - name: Install dependencies
        run: npm install

      # ビルドの実行
      - name: Run build
        run: npm run build

      # Lambdaにアップロード
      - name: Deploy to AWS Lambda
        run: |
          pip3 install awscli
          aws lambda update-function-code --function-name lambda-function-name --zip-file fileb://dist/package.zip
